In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("IMDB-Movie-Dataset(2023-1951) (1).csv")

In [3]:
df.shape

(2199, 8)

In [4]:
df.isnull().sum()

Unnamed: 0     0
movie_id       0
movie_name     0
year          65
genre          0
overview       0
director       0
cast           0
dtype: int64

In [5]:
df = df[['movie_id', 'movie_name', 'overview', 'genre', 'cast', 'director']]

In [6]:
df.head()

,movie_id,movie_name,overview,genre,cast,director
0,tt15354916,Jawan,A high-octane action thriller which outlines t...,"Action, Thriller","Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ...",Atlee
1,tt15748830,Jaane Jaan,A single mother and her daughter who commit a ...,"Crime, Drama, Mystery","Kareena Kapoor, Jaideep Ahlawat, Vijay Varma, ...",Sujoy Ghosh
2,tt11663228,Jailer,A retired jailer goes on a manhunt to find his...,"Action, Comedy, Crime","Rajinikanth, Mohanlal, Shivarajkumar, Jackie S...",Nelson Dilipkumar
3,tt14993250,Rocky Aur Rani Kii Prem Kahaani,Flamboyant Punjabi Rocky and intellectual Beng...,"Comedy, Drama, Family","Ranveer Singh, Alia Bhatt, Dharmendra, Shabana...",Karan Johar
4,tt15732324,OMG 2,An unhappy civilian asks the court to mandate ...,"Comedy, Drama","Pankaj Tripathi, Akshay Kumar, Yami Gautam, Pa...",Amit Rai

In [7]:
df['tags'] = df['overview'] + df['genre']+ df['cast'] + df['director']

In [8]:
df.head()

,movie_id,movie_name,overview,genre,cast,director,tags
0,tt15354916,Jawan,A high-octane action thriller which outlines t...,"Action, Thriller","Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ...",Atlee,A high-octane action thriller which outlines t...
1,tt15748830,Jaane Jaan,A single mother and her daughter who commit a ...,"Crime, Drama, Mystery","Kareena Kapoor, Jaideep Ahlawat, Vijay Varma, ...",Sujoy Ghosh,A single mother and her daughter who commit a ...
2,tt11663228,Jailer,A retired jailer goes on a manhunt to find his...,"Action, Comedy, Crime","Rajinikanth, Mohanlal, Shivarajkumar, Jackie S...",Nelson Dilipkumar,A retired jailer goes on a manhunt to find his...
3,tt14993250,Rocky Aur Rani Kii Prem Kahaani,Flamboyant Punjabi Rocky and intellectual Beng...,"Comedy, Drama, Family","Ranveer Singh, Alia Bhatt, Dharmendra, Shabana...",Karan Johar,Flamboyant Punjabi Rocky and intellectual Beng...
4,tt15732324,OMG 2,An unhappy civilian asks the court to mandate ...,"Comedy, Drama","Pankaj Tripathi, Akshay Kumar, Yami Gautam, Pa...",Amit Rai,An unhappy civilian asks the court to mandate ...

In [9]:
df.shape

(2199, 7)

In [10]:
df = df[['movie_id', 'movie_name', 'tags']]

In [11]:
df.rename(columns = {'movie_name':'title'}, inplace = True)

In [12]:
df['tags'] = df['tags'].apply(lambda x:x.lower())

In [13]:
df.head()

,movie_id,title,tags
0,tt15354916,Jawan,a high-octane action thriller which outlines t...
1,tt15748830,Jaane Jaan,a single mother and her daughter who commit a ...
2,tt11663228,Jailer,a retired jailer goes on a manhunt to find his...
3,tt14993250,Rocky Aur Rani Kii Prem Kahaani,flamboyant punjabi rocky and intellectual beng...
4,tt15732324,OMG 2,an unhappy civilian asks the court to mandate ...

In [15]:
import nltk

In [16]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [17]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [18]:
df['tags'] = df['tags'].apply(stem)

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=10000,stop_words='english')

In [20]:
vector = cv.fit_transform(df['tags']).toarray()

In [21]:
vector.shape

(2199, 10000)

In [22]:
cv.get_feature_names()

D:\Anaconda\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '10',
 '100',
 '102',
 '11',
 '12',
 '13',
 '14',
 '15',
 '151',
 '16',
 '16th',
 '17',
 '170',
 '1739',
 '1761',
 '18',
 '1825',
 '1857',
 '1897',
 '18th',
 '19',
 '1905',
 '1910',
 '1930',
 '1930s',
 '1940',
 '1940s',
 '1942',
 '1945',
 '1947',
 '1955',
 '1958',
 '1960',
 '1960s',
 '1962',
 '1967',
 '1968',
 '1970',
 '1970s',
 '1971',
 '1975',
 '1976',
 '1980',
 '1980s',
 '1982',
 '1983',
 '1984',
 '1986',
 '1990',
 '1990s',
 '1991',
 '1992',
 '1993',
 '1994',
 '1999',
 '19th',
 '1st',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2008',
 '2009',
 '2010animation',
 '2011',
 '2012',
 '2013',
 '2015',
 '2016',
 '2018',
 '2019',
 '2020',
 '2023',
 '2024',
 '21',
 '210',
 '213',
 '21st',
 '22',
 '23',
 '24',
 '25',
 '250',
 '25th',
 '26',
 '27',
 '28',
 '289',
 '2nd',
 '30',
 '300',
 '30th',
 '32',
 '34',
 '350',
 '359',
 '36',
 '40',
 '45th',
 '48',
 '4th',
 '50',
 '500',
 '55',
 '60',
 '600',
 '60s',
 '64',
 '65',
 '69',
 '6th',
 '70',
 '72',
 '73',
 '75',
 '786',
 '790',
 '80',
 '90',
 'aabid',
 'aachi',
 'aadam',
 'aadarsh',
 'aadhi',
 'aadhya',
 'aadukalam',
 'aahana',
 'aakanksha',
 'aakash',
 'aakeelbornila',
 'aakeelsujoy',
 'aakkash',
 'aakriti',
 'aakshath',
 'aalaap',
 'aaliya',
 'aamir',
 'aanand',
 'aanande',
 'aanchal',
 'aankhen',
 'aarav',
 'aarden',
 'aarti',
 'aaryan',
 'aaryananurag',
 'aashay',
 'aashhraf',
 'aashif',
 'aashim',
 'aashiqui',
 'aashish',
 'aashoo',
 'aasif',
 'aasokaaabhishek',
 'aathmika',
 'aayush',
 'aazam',
 'ab',
 'abandon',
 'abandoned',
 'abba',
 'abdali',
 'abdalladani',
 'abduct',
 'abductee',
 'abduction',
 'abductor',
 'abductors',
 'abdul',
 'abha',
 'abhay',
 'abhilash',
 'abhilashak',
 'abhimaan',
 'abhimanu',
 'abhimanyu',
 'abhinav',
 'abhinay',
 'abhinayar',
 'abhinetri',
 'abhishek',
 'abhisheksajid',
 'abhyankar',
 'abhyankarsachin',
 'abid',
 'abigail',
 'abil',
 'ability',
 'abinash',
 'abir',
 'abiran',
 'abl',
 'abnormal',
 'aboard',
 'aborted',
 'abortion',
 'abound',
 'abraham',
 'abrahambasu',
 'abrahambejoy',
 'abrahamravi',
 'abrahamsanjay',
 'abrahamshivam',
 'abrahamvish',
 'abrar',
 'abroad',
 'abscond',
 'absolut',
 'abu',
 'abudhar',
 'abus',
 'abuse',
 'academ',
 'academi',
 'academically',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accid',
 'accident',
 'accidents',
 'acclaim',
 'accompani',
 'accomplic',
 'accomplish',
 'accord',
 'account',
 'accus',
 'accused',
 'ace',
 'acharya',
 'acharyamohit',
 'achiev',
 'achint',
 'achrekarhasnain',
 'achyuth',
 'acid',
 'acp',
 'acquaint',
 'acquir',
 'act',
 'action',
 'actionaction',
 'actionamitabh',
 'actiondharmendra',
 'actiondhruva',
 'actiongavi',
 'actiongopichand',
 'actionkiara',
 'actionmahipal',
 'actionmithun',
 'actionnana',
 'actionprabhas',
 'actionr',
 'actionrahul',
 'actionrajesh',
 'actionrakul',
 'actions',
 'actionsapna',
 'actionsiddh',
 'actionvijay',
 'actionvika',
 'actionvinod',
 'actionvishal',
 'actionvivek',
 'actionvyjayanthimala',
 'activ',
 'activist',
 'activities',
 'activity',
 'actor',
 'actress',
 'actual',
 'ad',
 'ada',
 'adah',
 'adajania',
 'adam',
 'adapt',
 'adarkarnitya',
 'adarsh',
 'add',
 'addict',
 'addicts',
 'addit',
 'adeeb',
 'adept',
 'adesh',
 'adhaar',
 'adhikari',
 'adhikaribidisha',
 'adhikary',
 'adhyayan',
 'adi',
 'adib',
 'adil',
 'adithan',
 'aditi',
 'aditya',
 'adivasi',
 'adiya',
 'adiyaman',
 'adjust',
 'administ',
 'administration',
 'admir',
 'admirers',
 'admit',
 'adnan',
 'ado',
 'adolesc',
 'adopt',
 'adopted',
 'ador',
 'adrenalin',
 'adriann',
 'adrien',
 'adult',
 'adulteri',
 'adulthood',
 'adults',
 'advait',
 'advaita',
 'advanc',
 'advani',
 'advaniraj',
 'advantag',
 'advantageaction',
 'adventur',
 'adventure',
 'adventureaamir',
 'adventureakshay',
 'adventureamitabh',
 'adventurearun',
 'adventurebabloo',
 'adventurecomedy',
 'adventurejacki',
 'adventurekarthi',
 'adventurekathleen',
 'adventuremanoj',
 'adventuremithun',
 'adventurerajinikanth',
 'adventuresuniel',
 'adventureurvi',
 'adventurewasabi',
 'advers',
 'adversari',
 'advertis',
 'advis',
 'adwani',
 'adyasha',
 'aerial',
 'aeroplan',
 'afar',
 'affabl',
 'affair',
 'affairs',
 'affect',
 'affection',
 'affili',
 'affluence',
 'affluent',
 'afford',
 'afghan',
 'afghanistan',
 'afraid',
 'afran',
 'africa',
 'afrozan',
 'aftab',
 'aftermath',
 'afzal',
 'ag',
 'agarwal',
 'agarwallawr',
 'agashe',
 'agasherakeysh',
 'agasheshimit',
 'agastya',
 'age',
 'aged',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'ages',
 'aggarw',
 'aggarwal',
 'aggarwalraju',
 'aggarwalrohit',
 'aggriev',
 'agha',
 'aghagulzar',
 'aghas',
 'agiran',
 'agirideva',
 'agni',
 'agnihotri',
 'agnihotriatul',
 'agnihotridavid',
 'agnihotridevashish',
 'agnihotrie',
 'agnihotrik',
 'agnihotrikun',
 'agnihotrimanmohan',
 'agnihotrisantram',
 'agnihotrisikand',
 'agnihotrisubhash',
 'agnihotriyash',
 'ago',
 'agoni',
 'agoraphob',
 'agraw',
 'agrawal',
 'agre',
 'agree',
 'agrohari',
 'aham',
 'ahead',
 'ahimsa',
 'ahlawat',
 'ahlawatmaqbool',
 'ahluwalia',
 'ahluwaliashoojit',
 'ahluwaliateja',
 'ahm',
 'ahmad',
 'ahmed',
 'ahmedabad',
 'ahmedjasmin',
 'ahmedketan',
 'ahmer',
 'ahran',
 'ahsaa',
 'ahuja',
 'ahujajasbir',
 'ahujamohit',
 'ahujanikkhil',
 'ahujasooni',
 'aiappan',
 'aid',
 'ail',
 'ailment',
 'aim',
 'aimless',
 'aino',
 'air',
 'airbas',
 'airlin',
 'airplan',
 'airport',
 'airstrip',
 'aisha',
 'aishwarya',
 'aiyar',
 'aiyer',
 'ajaatshatru',
 'ajanta',
 'ajay',
 'ajaz',
 'ajinkya',
 'ajit',
 'ajmer',
 'ajooba',
 'ak',
 'aka',
 'akanksha',
 'akansha',
 'akarsh',
 'akash',
 'akashirfan',
 'akbar',
 'akel',
 'akerkar',
 'akerkarabhishek',
 'akhil',
 'akhilendra',
 'akhtar',
 'akira',
 'akkineni',
 'akkineniakarsh',
 'akkineniayan',
 'akram',
 'akshara',
 'akshat',
 'akshay',
 'akshya',
 'al',
 'aladin',
 'alagh',
 'alaghsiddharth',
 'alankrita',
 'alaya',
 'albeit',
 'albert',
 'albin',
 'albizuri',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alexand',
 'alexander',
 'alexx',
 'ali',
 'alia',
 'alibhai',
 'alien',
 'align',
 'alijayprad',
 'alik',
 'alina',
 'alinandita',
 'alisha',
 'aliv',
 'alive',
 'alizeh',
 'alka',
 'allah',
 'alleg',
 'alleged',
 'allegedli',
 'allegory',
 'allen',
 'alley',
 'alli',
 'allianc',
 'alloush',
 'allow',
 'alok',
 'aloke',
 'alon',
 'alongsid',
 'alreadi',
 'alt',
 'alter',
 'altermahesh',
 'alternavneet',
 'alumni',
 'alvi',
 'alway',
 'alzheim',
 'amal',
 'amala',
 'amalda',
 'amalgam',
 'aman',
 'amanda',
 'amar',
 'amara',
 'amardeep',
 'amarnath',
 'amass',
 'amateur',
 'amaz',
 'ambala',
 'ambani',
 'ambassador',
 'ambegaonkar',
 'ambegaonkarpaparao',
 'ambegaonkarpradeep',
 'amber',
 'ambika',
 'ambit',
 'ambiti',
 'ambition',
 'ambiye',
 'ambre',
 'ambrish',
 'ambust',
 'ameen',
 'ameesha',
 'ameeta',
 'america',
 'american',
 'ami',
 'amid',
 'amidst',
 'amin',
 'aminabhishek',
 'aminratnaa',
 'aminvipul',
 'amir',
 'amit',
 'amitabh',
 'amitoj',
 'amjad',
 'ammar',
 'ammtoj',
 'amnesia',
 'amnesiac',
 'amol',
 'ampute',
 'amrapurkar',
 'amrapurkaranil',
 'amrapurkarharmesh',
 'amrapurkarkundan',
 'amrapurkarmahesh',
 'amrapurkarshyam',
 'amrin',
 'amrish',
 'amrit',
 'amrita',
 'amrith',
 'amritha',
 'amritsar',
 'amrohimohit',
 'amruta',
 'amrutl',
 'amus',
 'amyra',
 'anahita',
 'anaika',
 'analysi',
 'anamika',
 'anand',
 'anandgauri',
 'anandi',
 'anandjai',
 'anandkalpataru',
 'anandmandeep',
 'anandmanish',
 'anandpramod',
 'anandpritesh',
 'anands',
 'anandvats',
 'anandvijay',
 'anangsha',
 'anant',
 'ananth',
 'anantvijay',
 'ananya',
 'anarkali',
 'anaspure',
 'anastasia',
 'ancestor',
 'ancestr',
 'anchal',
 'anchor',
 'ancient',
 'andaaz',
 'andaman',
 'anderson',
 'andhra',
 'andrea',
 'andronicu',
 'andronicus',
 'aneetahans',
 'aneja',
 'anew',
 'angad',
 'anganaanushre',
 'angara',
 'angel',
 'anger',
 'angira',
 'anglo',
 'angri',
 'ani',
 'aniket',
 'anil',
 'anim',
 'animal',
 'animation',
 'animationjigna',
 'animationmukesh',
 'animos',
 'anina',
 'anirban',
 'aniruddh',
 'anirudh',
 'anita',
 'anitha',
 'anjaan',
 'anjala',
 'anjali',
 'anjan',
 'anjani',
 'anjori',
 'anju',
 'anjuman',
 'ankit',
 'ankita',
 'ankolaraajeev',
 'ankur',
 'ankush',
 'anmol',
 'anmolsharan',
 'anna',
 'annapurna',
 'annatram',
 'anniversari',
 'anniversary',
 'announc',
 'annoy',
 'annu',
 'annual',
 'annually',
 'annuddin',
 'anonym',
 'anoop',
 'anoth',
 'ansh',
 'anshul',
 'anshuman',
 'answer',
 'answered',
 'answers',
 'antagonist',
 'antani',
 'antholog',
 'anti',
 'anticip',
 'antiqu',
 'antoni',
 'antonia',
 'antonio',
 'antony',
 'anu',
 'anubhav',
 'anuj',
 'anuja',
 'anup',
 'anupam',
 'anupama',
 'anupriya',
 'anuradha',
 'anurag',
 'anushka',
 'anwar',
 'anyarit',
 'anyon',
 'anyth',
 'aparajita',
 'aparna',
 'aparshakti',
 'apart',
 'apartment',
 'apathi',
 'apinderdeep',
 'apocalypt',
 'apoorva',
 'app',
 'appeal',
 'appear',
 'appetit',
 'appl',
 'appoint',
 'appointed',
 'apprehend',
 'apprentic',
 'approach',
 'approaches',
 'approv',
 'approve',
 'apps',
 'april',
 'apsara',
 'apte',
 'apurva',
 'arabian',
 'aradhana',
 'arav',
 'aravind',
 'arbaaz',
 'arch',
 'archaeolog',
 'archaeologist',
 'archana',
 'archanna',
 'archi',
 'archit',
 'architect',
 'arduou',
 'area',
 'areenah',
 'aren',
 'argument',
 'arid',
 'arif',
 'aris',
 'aristocrat',
 'arjan',
 'arjun',
 'arjunan',
 'arjunshank',
 'arm',
 'armaan',
 'arman',
 'armen',
 'armi',
 'arms',
 'army',
 'arnab',
 'arora',
 'aroraa',
 'aroraabhishek',
 'aroraanup',
 'arorabug',
 'aroradeepak',
 'arorak',
 'arorakabir',
 'aroramanmeet',
 'aroratanuja',
 'aroraterri',
 'aroravikram',
 'arquette',
 'arrang',
 'arranha',
 'array',
 'arrest',
 'arrested',
 'arrests',
 'arriv',
 'arrival',
 'arrivals',
 'arrives',
 'arriving',
 'arrog',
 'arrogance',
 'arrogant',
 'arsh',
 'arshad',
 'arson',
 'art',
 'arth',
 'arti',
 'artifact',
 'artist',
 'artistes',
 'arts',
 'arun',
 'aruna',
 'arunachal',
 'arunoday',
 'arunshyam',
 'arushi',
 'arvind',
 'arya',
 'aryam',
 'aryan',
 'aryapushpdeep',
 'aryasailesh',
 'aryavanshi',
 'aryeman',
 'ascend',
 'ascens',
 'asgar',
 'ash',
 'asha',
 'ashar',
 'asharamol',
 'ashay',
 'asheesh',
 'ashi',
 'ashish',
 'ashmit',
 'ashok',
 'ashoka',
 'ashokan',
 'ashokjamnani',
 'ashor',
 'ashrafadvait',
 'ashutosh',
 'ashwatthama',
 'ashwin',
 'ashwini',
 'asian',
 'asif',
 'asim',
 'asin',
 'ask',
 'askari',
 'askaribhappi',
 'askarishantaram',
 'aslam',
 'asma',
 'asoka',
 'asp',
 'aspects',
 'asperger',
 'aspir',
 'asrani',
 'asranib',
 'asranibasu',
 'asraniharri',
 'asraniirshad',
 'asranij',
 'asranimilap',
 'asranipriyadarshan',
 'asraniraghunath',
 'asranishakti',
 'asranivijay',
 'assail',
 'assam',
 'assassin',
 'assassinated',
 'assault',
 'assembl',
 'assertive',
 'assign',
 'assignment',
 'assist',
 'assistance',
 'associ',
 'assort',
 'assum',
 'astha',
 'asthana',
 'astound',
 'astrolog',
 'astronaut',
 'atal',
 'atheist',
 'athiya',
 'athlet',
 'athlete',
 'atkinson',
 'attach',
 'attack',
 'attacked',
 'attain',
 'attempt',
 'attenborough',
 'attend',
 'attent',
 'attitud',
 'attract',
 'atul',
 'aubrey',
 'audaci',
 'audit',
 'august',
 'augustin',
 'aulakh',
 'aunt',
 'aur',
 'aurangzeb',
 'auroshikha',
 'austen',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'auto',
 'avadh',
 'avaran',
 'avatar',
 'aveng',
 'averag',
 'avi',
 'aviat',
 'avika',
 'avinash',
 'avlani',
 'avneet',
 'avoid',
 'avro',
 'avrram',
 'avtaar',
 'avtar',
 'aw',
 'await',
 'awaken',
 'awakening',
 'awar',
 'award',
 'awarde',
 'awasthismita',
 'away',
 'awe',
 'awkward',
 'ayah',
 'ayan',
 'ayaz',
 'ayesha',
 'ayodhya',
 'ayr',
 'ayub',
 'ayurveda',
 'ayush',
 'ayushmann',
 'ayyub',
 'ayyubaanand',
 'ayyubkabir',
 'ayyubkun',
 'ayyubmeghna',
 'azad',
 'azhagam',
 'azhar',
 'azharuddinbiography',
 ...]

In [23]:
from sklearn.metrics.pairwise import cosine_similarity

In [24]:
similarity = cosine_similarity(vector)

In [25]:
similarity[0]

array([1.        , 0.04347826, 0.08340577, ..., 0.        , 0.        ,
       0.06512896])

In [26]:
def recommend(movie):
    movie_index = df[df['title'] == movie].index[0]
    distance = similarity[movie_index]
    movies_list = sorted(list(enumerate(distance)), reverse = True, key = lambda x:x[1])[1:6]
    for i in movies_list:
        print(df.iloc[i[0]].title)

In [77]:
recommend('Gandhi')

Netaji Subhas Chandra Bose: The Forgotten Hero
Mangal Pandey: The Rising
Swades: We, the People
Shabaash Mithu
Kaun Pravin Tambe?

In [78]:
import pickle

In [79]:
pickle.dump(df, open('bollywood_movie.pkl', 'wb'))

In [80]:
pickle.dump(df.to_dict(), open('bollywood_movies_dict.pkl', 'wb'))

In [81]:
pickle.dump(similarity, open('similarity2.pkl', 'wb'))